### ISSUE TITLE
Do you know about other dynamic fracture implementations?

### ISSUE THREAD

**Issue by D1no** [kainino0x/cis565final#3]
@kainino0x I stumbled over your CIS paper and was wondering if you are aware of standard gpu accelerated WebGL implementations of dynamic fracture systems / physics bases destruction models running from javascript?

I currently do research in that space of cross-device augmented reality engines.

Thank you for your input
Dino
hello@din.ooo

**Comment by kainino0x** [comment]
No, I'm not aware of any, sorry.

This project used WebCL (in addition to WebGL). WebCL has been a dead project for years (it was already dead by the time we did this project).

**Comment by kainino0x** [comment]
Note, today we have WebAssembly which allows native code to run portably in the web. I'm sure there are many CPU based native destruction engines out there, and you might be able to use Emscripten to compile one to the web.
