### ISSUE TITLE
do you think you could port this to upbge 0.3.0 / blender 2.8?

### ISSUE THREAD

**Issue by BluePrintRandom** [kainino0x/cis565final#4]
I would love to use this in game.

https://github.com/UPBGE/blender/tree/upbge0.3

**Comment by kainino0x** [comment]
No, sorry, we won't be doing a port. This was a school project and not maintained.

The technique is actually not that complex. Take a look at the original paper, _Real Time Dynamic Fracture with Volumetric Approximate Convex Decompositions_.

Note that the original technique is CPU-based, and in our project we ported it to GPU. There were negative consequences to the naive way that we ported it to GPU (we expand all "n-gons" out into many small triangles, without simplification, which results in exponentially increasing mesh complexity as multiple fractures are applied). The technique works best on CPU as originally designed, which also makes it simpler to implement.

That said, feel free to derive from our work if you'd like (even though it is modified for GPU and has these issues).
